# Generated by Django 6.1.1 on 2026-09-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('roadmap', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='job_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='jobs.jobanalysis'),
        ),
        migrations.AddField(
            model_name='goal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='phase',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='skills.skill'),
        ),
        migrations.CreateModel(
            name='SkillStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('Learn', 'Learn'), ('Practice', 'Practice'), ('Project', 'Project')], default='Learn', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='skills.skill')),
            ],
            options={
                'ordering': ['skill__name', 'order'],
            },
        ),
    ]
