# Generated by Django 6.1.1 on 2026-09-22 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.FloatField()),
                ('project_score', models.FloatField()),
                ('interview_score', models.FloatField()),
                ('portfolio_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
