# Generated by Django 6.1.1 on 2026-09-28 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('readiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinesssnapshot',
            name='job_analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='jobs.jobanalysis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readinesssnapshot',
            name='interview_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='readinesssnapshot',
            name='portfolio_score',
            field=models.FloatField(default=0),
        ),
    ]
