# Generated by Django 6.1.1 on 2026-09-29 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewquestion_target_role'),
        ('projects', '0002_project_imported_from_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='projects.project'),
        ),
    ]
