# Generated by Django 6.1.1 on 2026-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='detected_skills',
            field=models.ManyToManyField(blank=True, related_name='resumes', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects_text',
            field=models.TextField(blank=True),
        ),
    ]
